### ISSUE TITLE
apigw-custom-domain example fails to create the test.example.com domain

### ISSUE THREAD

**Issue by sayor-basu** [localstack/localstack-pro-samples#215]
Error during `make run`:

```
Serverless Domain Manager: Error: test.example.com:  Error: Could not find the certificate test.example.com.
 
 Error ---------------------------------------------------
 
  Error: Unable to create domain test.example.com
      at ServerlessCustomDomain.<anonymous> (/Users/sayorbasu/Autodesk/LocalStack_Experiments/localstack-pro-samples/apigw-custom-domain/node_modules/serverless-domain-manager/dist/src/index.js:182:23)
      at Generator.throw (<anonymous>)
      at rejected (/Users/sayorbasu/Autodesk/LocalStack_Experiments/localstack-pro-samples/apigw-custom-domain/node_modules/serverless-domain-manager/dist/src/index.js:6:65)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.22.12
     Framework Version:         2.72.3 (local)
     Plugin Version:            5.5.4
     SDK Version:               4.3.2
     Components Version:        3.18.2
```

root cause looks like during the `Importing local test certificate into ACM API ...` step, there is an error `Invalid base64: “server.crt”`. On investigation found that the migration to aws cli v2 would lead to this from [this](https://github.com/aws/aws-cli/issues/4978#issuecomment-592229037) suggestion

**Comment by alexrashed** [comment]
This issue has been fixed with your PR #216. Thanks for the report and especially for the PR to fix it! 🚀
