### ISSUE TITLE
"ecs-container-app" does not work

### ISSUE THREAD

**Issue by thanhtoan1196** [localstack/localstack-pro-samples#4]
Deploy the app locally via CloudFormation:
```
make deploy
```

Error
```
Creating ECS infrastructure locally

Unable to parse response (syntax error: line 1, column 54), invalid XML received:
b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>\n'
Deploying ECS app to local environment
Using default tag: latest
latest: Pulling from library/nginx
Digest: sha256:922c815aa4df050d4df476e92daed4231f466acc8ee90e0e774951b0fd7195a4
Status: Image is up to date for nginx:latest
docker.io/library/nginx:latest

An error occurred (ExportNotFound) when calling the CreateStack operation: No export named infra:ECSTaskExecutionRole found.
```
Log
```
019-11-06T04:27:51:WARNING:localstack.utils.cloudformation.template_deployer: Unexpected resource type EC2::VPC when resolving references of resource VPC: {'Type': 'AWS::EC2::VPC', 'Properties': {'EnableDnsSupport': True, 'EnableDnsHostnames': True, 'CidrBlock': '10.0.1.0/16'}}
2019-11-06T04:27:51:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "VPC": argument of type 'NoneType' is not iterable Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 166, in parse_and_create_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 257, in _parse_and_create_resource
    new_res_id = find_id(result)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 251, in find_id
    if id_attr in resource:
TypeError: argument of type 'NoneType' is not iterable

2019-11-06T04:27:59:ERROR:localstack.services.cloudformation.cloudformation_starter: Unable to parse and create resource "TaskDefinition": 400 Bad Request: <ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>ExportNotFound</Code>
    <Message>No export named infra:ECSTaskExecutionRole found.</Message>
  </Error>
  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>
</ErrorResponse> Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 166, in parse_and_create_resource
    return _parse_and_create_resource(logical_id, resource_json, resources_map, region_name)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 192, in _parse_and_create_resource
    resource_tuple = parsing.parse_resource(logical_id, resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/parsing.py", line 279, in parse_resource
    resource_json = clean_json(resource_json, resources_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 145, in clean_json
    result = clean_json_orig(resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/parsing.py", line 229, in clean_json
    cleaned_val = clean_json(value, resources_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 145, in clean_json
    result = clean_json_orig(resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/parsing.py", line 229, in clean_json
    cleaned_val = clean_json(value, resources_map)
  File "/opt/code/localstack/localstack/services/cloudformation/cloudformation_starter.py", line 145, in clean_json
    result = clean_json_orig(resource_json, resources_map)
  File "/opt/code/localstack/.venv/lib/python3.6/site-packages/moto/cloudformation/parsing.py", line 217, in clean_json
    raise ExportNotFound(cleaned_val)
moto.cloudformation.exceptions.ExportNotFound: 400 Bad Request: <ErrorResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <Error>
    <Type>Sender</Type>
    <Code>ExportNotFound</Code>
    <Message>No export named infra:ECSTaskExecutionRole found.</Message>
  </Error>
  <RequestId>cf4c737e-5ae2-11e4-a7c9-ad44eEXAMPLE</RequestId>
</ErrorResponse>
```

**Comment by whummer** [comment]
Thanks for reporting - @thanhtoan1196 . Turns out that the `ec2` API is required to deploy the ECS app (to create `AWS::EC2::SecurityGroup` and other CloudFormation resources).

The README has been updated to reflect this. Thanks
