### ISSUE TITLE
Using packer create ami fail

### ISSUE THREAD

**Issue by sunyinghao5438** [localstack/localstack-pro-samples#6]
```
2020-04-09T15:42:32:ERROR:localstack.services.generic_proxy: Error forwarding request: MyHTTPConnectionPool(host='192.168.65.2', port=4535): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5314dc8310>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5314dc8310>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='192.168.65.2', port=4535): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5314dc8310>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 303, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 190, in return_response
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 160, in run_vm_instance
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 198, in get_vm_manager
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 241, in call_local_daemon
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='192.168.65.2', port=4535): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5314dc8310>: Failed to establish a new connection: [Errno 111] Connection refused'))

2020-04-09 15:42:33,602:API: 127.0.0.1 - - [09/Apr/2020 15:42:33] "POST / HTTP/1.1" 200 -
2020-04-09 15:42:33,602:API: 127.0.0.1 - - [09/Apr/2020 15:42:33] "POST / HTTP/1.1" 200 -
2020-04-09 15:42:33,602:API: 127.0.0.1 - - [09/Apr/2020 15:42:33] "POST / HTTP/1.1" 200 -
2020-04-09T15:42:33:INFO:localstack_ext.services.ec2.ec2_listener: Sending request to start new VM instance to local daemon
2020-04-09T15:42:33:ERROR:localstack.services.generic_proxy: Error forwarding request: MyHTTPConnectionPool(host='192.168.65.2', port=4535): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5314b49a90>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.8/http/client.py", line 1230, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1276, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1225, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1004, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 944, in send
    self.connect()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 184, in connect
    conn = self._new_conn()
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 168, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5314b49a90>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: MyHTTPConnectionPool(host='192.168.65.2', port=4535): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5314b49a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/code/localstack/localstack/services/generic_proxy.py", line 303, in forward
    updated_response = self.proxy.update_listener.return_response(**kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 190, in return_response
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 160, in run_vm_instance
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 198, in get_vm_manager
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/localstack_ext/services/ec2/ec2_listener.py", line 241, in call_local_daemon
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: MyHTTPConnectionPool(host='192.168.65.2', port=4535): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5314b49a90>: Failed to establish a new connection: [Errno 111] Connection refused'))

2020-04-09 15:42:34,930:API: 127.0.0.1 - - [09/Apr/2020 15:42:34] "POST / HTTP/1.1" 200 -
2020-04-09 15:42:34,930:API: 127.0.0.1 - - [09/Apr/2020 15:42:34] "POST / HTTP/1.1" 200 -
2020-04-09 15:42:34,930:API: 127.0.0.1 - - [09/Apr/2020 15:42:34] "POST / HTTP/1.1" 200 -
2020-04-09T15:42:34:INFO:localstack_ext.services.ec2.ec2_listener: Sending request to start new VM instance to local daemon
2020-04-09T15:42:34:ERROR:localstack.services.generic_proxy: Error forwarding request: MyHTTPConnectionPool(host='192.168.65.2', port=4535): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5314b49a00>: Failed to establish a new connection: [Errno 111] Connection refused')) Traceback (most recent call last):
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/connection.py", line 156, in _new_conn
    conn = connection.create_connection(
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/opt/code/localstack/.venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

```
amazon-ebs: output will be in this color.

==> amazon-ebs: Prevalidating any provided VPC information
==> amazon-ebs: Prevalidating AMI Name: amzn2_modified_ami
==> amazon-ebs: Pausing after run of step 'StepPreValidate'. Press enter to continue. 
    amazon-ebs: Found Image ID: ami-c3d02913
==> amazon-ebs: Pausing after run of step 'StepSourceAMIInfo'. Press enter to continue. 
==> amazon-ebs: Pausing after run of step 'StepNetworkInfo'. Press enter to continue. 
==> amazon-ebs: Using existing SSH private key
==> amazon-ebs: Pausing after run of step 'StepKeyPair'. Press enter to continue. 
==> amazon-ebs: Creating temporary security group for this instance: packer_5e8f4262-c4e1-213e-5e09-21a337b019ff
==> amazon-ebs: Authorizing access to port 22 from [0.0.0.0/0] in the temporary security groups...
==> amazon-ebs: Pausing after run of step 'StepSecurityGroup'. Press enter to continue. 
==> amazon-ebs: Pausing after run of step 'StepIamInstanceProfile'. Press enter to continue. 
==> amazon-ebs: Pausing after run of step 'StepCleanupVolumes'. Press enter to continue. 
==> amazon-ebs: Launching a source AWS instance...
==> amazon-ebs: Adding tags to source instance
    amazon-ebs: Adding tag: "Name": "Packer Builder"
==> amazon-ebs: Error launching source instance: : 
==> amazon-ebs: 	status code: 502, request id:
==> amazon-ebs: Pausing before cleanup of step 'StepCleanupVolumes'. Press enter to continue. \ 
==> amazon-ebs: No volumes to clean up, skipping
==> amazon-ebs: Pausing before cleanup of step 'StepIamInstanceProfile'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepSecurityGroup'. Press enter to continue. 
==> amazon-ebs: Deleting temporary security group...
==> amazon-ebs: Pausing before cleanup of step 'StepKeyPair'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepNetworkInfo'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepSourceAMIInfo'. Press enter to continue. 
==> amazon-ebs: Pausing before cleanup of step 'StepPreValidate'. Press enter to continue. 
Build 'amazon-ebs' errored: Error launching source instance: : 
	status code: 502, request id: 

==> Some builds didn't complete successfully and had errors:
--> amazon-ebs: Error launching source instance: : 
	status code: 502, request id: 

```

**Comment by whummer** [comment]
Hi @sunyinghao5438 , thanks for reporting this issue. Can you please help us debug this issue a bit more by providing some details about your environment setup.

Which operating system are you using?

The EC2 API requires us to launch a small daemon process on the local machine, which then communicates with the LocalStack Docker container to start EC2 virtual machines. Are you seeing something like this in your log output on startup? 
```
2020-04-11T14:04:04:INFO:local_daemon: Attempting to obtain sudo privileges for local daemon of EC2 API (required to start SSH forward proxy on privileged port 22). You may be asked for your sudo password.
```

When you run the example, can you please inspect the running processes on your machine? There should be a `local_daemon.py` process running on your machine. If you're on a Mac/Linux machine, the following command can help:
```
$ ps aux | grep local_daemon
username          66267   0.0  0.0  4313952   7424   ??  Ss    2:04PM   0:00.43 python .../localstack_ext/bootstrap/local_daemon.py
...
```

We'll be happy to debug this issue in more detail with you. Did you receive an invite to join our community on Slack? Please reach out to us, so we can help you in more detail here. Thanks!

**Comment by sunyinghao5438** [comment]
@whummer  Thank you for your reply. 
I did not saw the info about INFO:local_daemon
And there is no `local_daemon.py`  process running on my machine.
I just joined Slack, could I message you on slack and ask for help in more detail?

**Comment by whummer** [comment]
Thanks again @sunyinghao5438 . I think we were able to resolve this issue together with you, at least with a workaround that seems to be working for you for now. Let's continue to debug this via Slack if there are any other issues. Thanks!

**Comment by moetw2002** [comment]
hello @whummer 

I have the same issue. I am using docker-compose to bring up the services. An excerpt from my docker-compose is below.

```
  localstack-configurator:
        build: "./localstack"
        depends_on:
          - postgresql-configurator
        ports:
          - "4566-4597:4566-4597"
          - "${PORT_WEB_UI-8083}:${PORT_WEB_UI-8080}"
        environment:
          - SERVICES=s3,lambda,sqs
          - DEBUG=1
          - PORT_WEB_UI=${PORT_WEB_UI- }
          - LAMBDA_EXECUTOR=docker
          - DOCKER_HOST=unix:///var/run/docker.sock
          - DEFAULT_REGION=us-east-1
          - HOSTNAME_EXTERNAL=localstack-mmc
          - AWS_ACCESS_KEY_ID=mmc
          - AWS_SECRET_ACCESS_KEY=mmc
          - AWS_DEFAULT_REGION=us-east-1
          - COUNTRIES=gb es nl pt ca
          - HOST_TMP_FOLDER=${TMPDIR}
        volumes:
          - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
          - "/var/run/docker.sock:/var/run/docker.sock"
        networks:
          backend:
            aliases:
              - localstack-mmc
```
In addition I have 3 other services as part of this docker-compose i.e. 
-  postgres image 
-  postgres adminer
- the app that i am working on (spring boot app which is running on embedded tomcat)
